### ISSUE TITLE
Too many variables, need help.

### ISSUE THREAD

**Issue by gaoryrt** [LingDong-/wenyan-lang#119]
Brilliant repo!
I was trying to write a fib function, but I got too many variables, is there anyway avoiding it? 

Here's my fib code:
```
吾有一術。名之曰「斐波那契」。
欲行是術。必先得一數。曰「囊」。乃行是術曰。
若囊小於三者。
  乃得一。
若非。
  減囊以一。名之曰「甲」。
  施「斐波那契」於甲名之曰「左」。
  減甲以一。名之曰「乙」。
  施「斐波那契」於乙名之曰「右」。
  加左於右名之曰「答」
  乃得「答」也。
是謂「斐波那契」之術也。
```
Can I do the same thing without declaring `甲` `乙` `左` `右`?

**Comment by gaoryrt** [comment]
```
return fib(num - 1) + fib(num - 2)
```
Could it be like `乃得加「施「斐波那契」於「減囊以一」」以「施「斐波那契」於「減囊以二」」` or something?

**Comment by LingDong-** [comment]
Hi there, you could use 其 to refer to the previous temporary variable. More documentation on that soon.
I would avoid nested quotes `「」` because from a literary perspective, it makes the code too "programming-language-like" and not "Classical Chinese" enough.

Thanks a lot for your suggestion though!

**Comment by gaoryrt** [comment]
Appreciate that!
