### ISSUE TITLE
How to input 「「 and 」」

### ISSUE THREAD

**Issue by AshyAzure** [LingDong-/wenyan-lang#186]
Is there any alternative to input 「「問天地好在」」？
Inputing  "「「"   on Mac is quite difficult.
When I type shift+{  and  shift+{ , it will be 「『  instead of「「

**Comment by antfu** [comment]
I think it's duplicate to #19

If you are using VSCode, you can try [this extension for Wenyan](https://github.com/antfu/wenyan-lang-vscode).

It will replace punctuations automatically as you type.

![](https://github.com/antfu/wenyan-lang-vscode/raw/master/screenshots/demo-punctuations.gif)

**Comment by AshyAzure** [comment]
Thx!!

**Comment by heangfat** [comment]
This is just the normal quotation marks for Chinese (and also Japanese and Korean).
「中日韓文引號」
Since you are using Mac, I personally suggest you to use [鼠鬚管](https://rime.im/). This is a cross-platform open source input method, also known as 中州韻 on Linux, 小狼毫 on Windows, and 同文 on Android. It will be very simple to input these CJK quotation marks, both「單引號」and『雙引號』.

**Comment by AshyAzure** [comment]
@heangfat Thx！I will try it
