### ISSUE TITLE
代码文件扩展名

### ISSUE THREAD

**Issue by antfu** [LingDong-/wenyan-lang#30]
刚刚做了一个 VSCode 插件 https://github.com/antfu/wenyan-lang-vscode

目前仓库的样例里采用txt作为文件拓展名，不便于编辑器辨认语言，希望可以确定一个专用的代码文件扩展名。

Proposal:
- `wyw`
- `wyl`
- `wenyan`

**Comment by LingDong-** [comment]
Indeed we need a standard extension!

But how about 

```
wy
``` 

Since there are `py`, `js`, `rb`, `go`, `pl`... Two letter acronyms seems to be in fashion now. And it seems that the `wy` is [not used by other documents](https://en.wikipedia.org/wiki/List_of_filename_extensions_(S%E2%80%93Z)).

Thanks a lot for your VSCode extension, it looks very nice. I've put a link to it in the README along with attribution to you: 57acbfe66147b2d174023c285ee5c473aa44a047

**Comment by antfu** [comment]
`wy` looks great! I was just wondering where to check the usage of extensions. 😂

>  I've put a link to it in the README along with attribution to you

Much appreciated! I just built it in a couple of hours. I would enhance it furthermore. Whenever you have decided which extension to use, I would update the vscode extension as well.

Thanks for the great work! Love your prologue btw,

**Comment by LingDong-** [comment]
Just changed all the extensions to `wy`. (Hopefully nothing breaks)
fde2ada807ffe6d2dfb313bc77c83b605808c34f

Thanks, glad you enjoyed the project.
