### ISSUE TITLE
How do I initialize/assign to a module export variable?

### ISSUE THREAD

**Issue by statementreply** [LingDong-/wenyan-lang#340]
Initialization:

`施「求圓周率」。名之曰「甲」。今有一數。曰「甲」。名之曰「圓周率」。` works.

`施「求圓周率」。今有一數。曰其。名之曰「圓周率」。` doesn't work.

Assignment:

`今有一數。曰三。名之曰「圓周率」。施「求圓周率」。昔之「圓周率」者。今其是矣。` assigns only the local variable, but not the exported.

**Comment by LingDong-** [comment]
Hi, thanks for bringing this up!

The second example doesn't work because of `曰其`. `其` is not supported here because the sentence sounds awkward in Classical Chinese. What you can do is:

```
施「求圓周率」。名之曰「吾之圓周率」。
今有一數。曰「吾之圓周率」。名之曰「天下人之圓周率」。
```

Whether I should allow it but discourage it is a good question. Let me think about this.

For assignment to work, I have to track which variables are declared as an exported variable, and later when you assign to it, add the `this.` prefix too. This is easy, but problem is I also need to worry about scoping, e.g. when you have a function inside a module in which declares a local variable of the same etc.

Another issue is that `this.` refers to the current scope, which means that I'll need to save `this.` as `that.` at the beginning of every module, and use `that.` instead when inside closures. But the question is should `今有` understood as `moudule.exports` or should classes (coming soon) also be able to use `今有` to make public attributes.

So probably think of `今有` as a const for now. One shouldn't need to assign to it regularly. In fact, one should assign to it when the item is ready to export :)

Thank you
