### ISSUE TITLE
library and <script src="...." >

### ISSUE THREAD

**Issue by gorgorgordon** [LingDong-/wenyan-lang#377]
能不能做成一個可以在HTML <script src="..." > 導入的library?

**Comment by LingDong-** [comment]
Hi @gorgorgordon , I think it is possible. `parser.compile` takes in an option called reader, which is a function that specifies how to read a user-imported module. By default it uses node's `fs.readFileSync`. When in a browser, if your code of your library is already inside the `<script>` tag (not in `src=`), you can do this:
```js
var reader = function(lib_id){
  return document.body.getElementById(lib_id).innerText;
}
compile(...,...,{reader,...})
```
If the library's code is in `src="url"`, it'll be slightly more complicated since you'll need to write a request to fetch that text and feed it to the compiler, using the `reader` option.

Thanks!
